// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToDo.DataAccess.Data;

#nullable disable

namespace ToDo.DataAccess.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20251016153615_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToDo.Models.Models.TDTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CompletionPercentage")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TDTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletionPercentage = 30.0,
                            Description = "Description1",
                            ExpirationDate = new DateTime(2025, 10, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProgress",
                            Title = "Task1"
                        },
                        new
                        {
                            Id = 2,
                            CompletionPercentage = 40.0,
                            Description = "Description2",
                            ExpirationDate = new DateTime(2025, 10, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProgress",
                            Title = "Task2"
                        },
                        new
                        {
                            Id = 3,
                            CompletionPercentage = 50.0,
                            Description = "Description3",
                            ExpirationDate = new DateTime(2025, 10, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProgress",
                            Title = "Task3"
                        },
                        new
                        {
                            Id = 4,
                            CompletionPercentage = 60.0,
                            Description = "Description4",
                            ExpirationDate = new DateTime(2025, 10, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProgress",
                            Title = "Task4"
                        },
                        new
                        {
                            Id = 5,
                            CompletionPercentage = 70.0,
                            Description = "Description5",
                            ExpirationDate = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProgress",
                            Title = "Task5"
                        },
                        new
                        {
                            Id = 6,
                            CompletionPercentage = 80.0,
                            Description = "Description6",
                            ExpirationDate = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProgress",
                            Title = "Task6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
